# Get a base image, in this case Debian
FROM debian:latest

#Practice environment variable for release updates use dollar sign with variable name in use
ENV S6_RELEASE 1.21.4.0

# Installs S6 Overlay Process Manager
ADD https://github.com/just-containers/s6-overlay/releases/download/v$S6_RELEASE/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

# Copy the install script into the Container to be executed on startup
COPY install.sh /etc/content-init.d/
RUN chmod u+x /etc/cont-init.d/install.sh #change mode user plus execute to add execute permissions

#Last thing we need is where to enter the container to start initiatlize
ENTRYPOINT ["/init"]
